server:
    port: 8081
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        queue: user.queue
        template:
            exchange: user.exchange
            routing-key: user.routing-key